name: "Push actions"

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Check push
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install project and test dependencies
        run: pip install -e ".[test]" black

      - run: python3 -m black .

      - name: Run tests
        run: python3 -m pytest
