name: "Push actions"

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Check push
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: python -m pip install aiohttp numpy black pytest pytest-asyncio

      - run: python3 -m black .

      - name: Install project
        run: pip install -e .

      - name: Run tests
        run: python3 -m pytest
